In [1]:
import pandas as pd
df = pd.read_csv("D:/Learn_ML/ML_algos/datasets/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
y = df["Species"]
X = df.drop(columns=['Id' , 'Species'])

In [3]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)

In [7]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)

In [8]:
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()
print(y_train)
print(y_test)

['Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
['Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor']

In [11]:

y_train.dtype

dtype('O')

In [12]:
y_train = y_train.reshape(-1 , 1)
y_test = y_test.reshape(-1 , 1)

In [13]:
import numpy as np

In [21]:
def euclidean_distance(x1 , x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

def knn_predict(X_train, y_train, x_query, k):
    distances = []
    for i in range(len(X_train)):
        dist = euclidean_distance(X_train[i], x_query)
        distances.append((dist, y_train[i].item()))
    distances.sort(key = lambda x : x[0])
    top_k = distances[:k]
    labels = [label for _, label in top_k]
    prediction = max(set(labels), key=labels.count)
    return prediction

In [22]:
k = np.sqrt(X_train.shape[0])

In [23]:
results = []
for i in range(len(X_test)):
    pred = knn_predict(X_train, y_train, X_test[i], k=5)
    results.append(pred)

In [29]:
results

['Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor']

In [30]:
y_test.shape

(30, 1)

In [31]:
output = pd.DataFrame(
    {
        "correct" : y_test.ravel() ,
        "prediction" : results
    }
    
)

In [32]:
output

            correct       prediction
0       Iris-setosa      Iris-setosa
1    Iris-virginica   Iris-virginica
2    Iris-virginica   Iris-virginica
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5    Iris-virginica   Iris-virginica
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13   Iris-virginica   Iris-virginica
14  Iris-versicolor  Iris-versicolor
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17      Iris-setosa      Iris-setosa
18  Iris-versicolor  Iris-versicolor
19      Iris-setosa      Iris-setosa
20  Iris-versicolor   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24      Iris-setosa      Iris-setosa
25      Iris-setosa      Iris-setosa
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29  Iris-versicolor  Iris-versicolor

In [33]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, results)
print(cm)

[[12  0  0]
 [ 0  9  1]
 [ 0  0  8]]